sudo: false
language: node_js
node_js:
- node
script:
- yarn lint
- yarn flow
- yarn check
- yarn browsertest
- yarn coverage
dist: trusty
sudo: false
os: linux
addons:
  apt:
    packages:
      - xvfb
before_script:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
env:
  matrix:
    secure: pu+Ia+KRh9CdjXwCYNQ2/2uXoUoZ6k8uMNIgJ39+Qr5FSrhvlzuoHjNjuXrm/gRz4pO7vsXr7Fmr68X9oeMoDm8L8tb7dEIuoL7ti1dlVUt/PvdFcSadyIt/+xCpMjv6oA3rKulQfJbXQSahwciqWCt1zhXVXn6PLRFS2hdh/IeZWLjDrzLHDK0Qk/+PUfe5Wk6S9m8h5vt3RiVCCpAuJJz6UuOCfvrYegb0DhvxuIuDtKA5uC9LOkFsXYSX1RZoVStxikAZaPYrYN1R7FK8PlC/4+TiCvD4NVhcqPBL2CyLtCV6S12TMB2O26b8ROYATlSEB1O7snJf+BB3NJWrTAAqWWW6KveqZa1THJwK5gXj7pkSkBIVp6A2I0zb/vlnNiWVAleTgT8EVtTyGbtlFk8BQjIL+ou7ucTNhi2GGP7kyPxrDiLTGzQVb0wW9MaQDYtkFp1Ji2ijF6/3B09fwFG1ShBB4Tqokxr+eRB53h8UXl0pfQyIduIHNg/ucqD242uGoP8fqt+PFHTcFexLM2/6W8NS/fIqXnDkdy4WZsPHT45Dz1iPEVKQ6qJw/vmSrz1qCGqga22ShecuLhsJOYs4LrH1Hi0/2tCmZ36T2G77CviI+tKjzp307X52tEUmRbPcqGwoR58/6bM7ClQaUeE2J3Dm7DxhOr4bcT6TGgA=

before_deploy:
  - zip -q -r latest *
  - mkdir -p deploy_code_upload
  - "mv latest.zip deploy_code_upload/$TRAVIS_COMMIT.zip"

deploy:
  # Staging continuous deployment
  - provider: s3
    access_key_id: &access_key_id_staging
      secure: "0cUgenowgPhqwpSwnTbc3eITcLdKBzVKNy6RpFO23yj/V7CoJ6TbC2L1IutRwu4Pf5soQ4zOHcZ87WRA38BvUS9wjj4eUcplWgg6z9SrbomwfKKiUcXam9gQZd3Rlzi378Qi06ZkLiaHMZNeCEwGFDlZCJ5fc9ary5Pj5SokwFzt6hi7NdtEftdaLtGzN7YZhvDW5OYVXdzSkYOpSjXcU22HEU6uQ8RXocXRQSz0mxvbCGejHfTXCxfocFG2n0PHoslBdY9XLCEz4fih0RminpMLtGaNPtC4KlxiVNB3cdekT8yGFQdL4w8qy+PsUYyKZ9w6hYDyUWVe6I9MYCRS1/w7SLJ2raAEnR/i46RQ55jk8tXyj4/UqB/MysvhQ2/+EEg9eRaAFvLKOW6MtHsZGLoamHnCKqHgWz4G5xCKq4KHPubQAgAmqLPPlWHLpGpt52NOZWzhIu+X2x/Z2HFEQgEwqjdYs+Ht9ad4u9SzRQSOtHUlY30gzV41rpkSNTVKECwPnLuKIp7NZNfNqvCoAu3I3XXNpyMNM4jdm0qzdIVpJ0iBE84bo1jSOIrRoc1bP/BDApy6rWDr8kmf3RWEkKkz5dyy2dbS4t6LRvoVG7CoZ6DMR1ArMqsbAQufMuA8f7Lt1jJhS6S/XcXudb8WbkdJqz7AI+3bAuomKF4wPlk="
    secret_access_key: &secret_access_key_staging
      secure: "dh8nMWvu5r0kvy2dJQ8p2U3g8DjJwoiuvr2oxS4N2vRCId9tqLg9G0No68grakEpewhJUESuyf7ns729JZQPYQCtKoKqLEux0Ym+UujTNzcfma/YllUNMi81hMIaa8HQ0+O1j29sThlfaIaFc9zoho9D2CZw8ILDdGhJeShWgN82MyyX7t3lToNIvyIX+TN9ZrXmuWuvlFajJx5v5f1PKpclWiVqIr8prf1PRRkikNJE0fw/B5gUcVp2Fyhpr65YnZOGMsFL4pEzK5dXK0XJiBeT7gd3Tx5noEz1n1bWpuMrPhe77v4/nLCdrl+ytE8lNs7yqirgZ8lrl7LaJ/4WfakZtDFzNf9yvnkW4Gt0yom34U8VhZ0fGY1nDRrLFcYNv6h3XtacaWBg3xVsL5kz/EL/nnNYqOL+PoXH952oEMIpNRtglrggVnqcuvmuKueYUx5xmVh2BZ6LHjM7oLfYCD3P62AyxcDDT4UIL5RJRaLuahWjSiLl2fT5PLWdO3xISYo83L/k7Rp4iuHCNe/R6qmMaf5Vfc9XpCH4KEBDvzAr8KKg4VKQJ8F1hvm7Tr+AiUgIaAOj6ALo4QuXueIBK3hdSm2SyZ9NXrRhmluA7ChFdXhgPnHWOOYBFj5FzACz6kEewV1sek8I9dJoS6USaUU479RNRSwhuZR0AlAipUw="
    local_dir: deploy_code_upload
    skip_cleanup: true
    on: &deploy_on_staging
      branch: staging
    bucket: &s3_bucket_staging
      secure: "soPxr/H5fNiDNa4hppQOXdNG6qjPaw023MyQ55/jgYWhd5SoJ0D5azvF9Q5+JQMOT/dsofGQDKLtI7nEA9jBUVSyP7V+gx87ZcsoY7bDmzEaq3NY2xzRX0g30oZ7BHpgiknBL3OpqtyXgywVcpm80COb4w3f2v4kVvCm10b8cSwE1J/JLqcGSx70npTYMQE/g93exME5652vfFmDwluBc1qcoec6inceE/EbyXZpozqoiof08vJc+jLSlRIB2V2ylPJ8s9OGaYBe0YbpPsB281R2cRMwwjbxqP187z3FQIUvsVKx/K9HHeg13U+H8pGyawsUaIJTPRLKOypxcTNavopCpOSDAwR7nhnee1Xfc3t8znAtK+5THqMMjliBPTHUVenUDdGjSM8nyqaRdGD4PU4IeYXSkKyPqvh0S/5Dxi6VMkdNLlk2mVRVGGHkCbXTZjb8q2DRb+R4UPimfVaw6F0IIIXcHHp2JrbJ9tsedvubWGEH6P9wwxquw4sm3dsLIv8OrrCm9SHpaFkSUklXN62IIxGKmISe1O+DkFKFXQUs3LcIwJ02wcjjPJ9pf38KxAGpe+3yqiNGgmgN0XWKg3WwCx+fIDqTBweNplhMTMrLte+E5lz5hTbnFo9mFVUUMRRDMuH4gaCO2ZgDH4XCZYXDnju+gd/KB/SXZKIroX0="
    region: us-west-2
  - provider: codedeploy
    access_key_id: *access_key_id_staging
    secret_access_key: *secret_access_key_staging
    bucket: *s3_bucket_staging
    region: us-west-2
    key: "$TRAVIS_COMMIT.zip"
    bundle_type: zip
    application: &application_staging
      secure: "szhdBMyKVqnUl6PG3inA9APL1Fgeck8RcGYwhK1WlkmkdtMefAMpxVrC1hfJFM7uMIyZuQv58T8QDs+FtAvtBIaa7EUHgaVtjsjiRkJqZbnbRSTY2znfHjsmhXL20cMsvudLxKO1XFk798AgmQAaIQbB/NcaVWqI7M2C27p8f+JMtaKVKW0sX9i9MdaRM1UfynArcrfoVCNMGmjJb1hAy+a9QPfGcjVX26KEhEksYeiFxTvuk4LsWGs9gXxv9JTqENFkoXmCq/PVFH0x/+wY1ACNQTAm/bNzeXBqaqJEJ5NYscSrX9IogsjYrSXxe0h3d8QheYvejdnpyIWLI92sPmMAJtoTBAWI2NGymnywNYej153M5PJQkeMKbIaus+5fUKcrG7uHzSw/WDk5a6Nuo8XfsCpXxsZCZtGFmzQZUOkylvA1FK+mWp4gAoLXor2/hTx0jdJa9EQ5o2Nis4un9Rq+TCB9ymFxG/5OvHx7hoKu2sw9tLniXIMs19pyWl82+LXb4EspWV9v0ZuZHnfK+1Xmmx8QXfV0x1TN3huyQ5d0sTJw35muPNdXQFmCBBh3oEGK+0wrIjNtwP5f0Koqd/9D6DeFGltVMKOVUww4j8xukF3UNae/RpasKLXb5E1QoOldw5XiU5dSnwGIkULAk/8pG4sRabuYZCYGUOQYtGQ="
    deployment_group: *application_staging
    on: *deploy_on_staging
  # Prod continuous deployment
  - provider: s3
    access_key_id: &access_key_id_production
      secure: "LWurtU7hC+bed4WB7RLQzF2gfkIW1YA+CHgiDnX1cyMB0uPEbH5J86wAsWmm6xz82tR7mZcpoLPOgMd5+PLSyXwMfYUhl/w0W7oIgduZetUT28Zw9Wr2Iy48SOw3xZZaTmxmvCMYxFZAS48C+yoP4QwJahwXddFPcHsM3BlbKXGplksVtZiwPAVmjkgQ2p3W6GuaOzMDSbGHVYwJBUw+mlCHO8rZdEN/7NRimS6IJ8w3xkMMHN87O/7f5o3d8k80IqKNFO5ub8dw0bdbl+lnyI7C61mrWkQJFOzB2hZETjYhaQE9cioZYFp8CSU7qKtdRO+uFVWwutsfZ3zj0YyBt2Dp9kyDnqCYbK8PCVfcsb//WAX7iGN1w8Upv3OT6iorpBE/0PSZhYgV+lYi0HXW6kznbQROnCqQSGKj0s4fXAdheGfpvpijkiG5rXZd3gB8oAqgsG5BCKppQVTdtytR+/tr/2YJk1An6oU6lB/G+EoqYRUWTPwBxT56WLUoWaxVUXMctapKgdfhgMMBk1S82YVMrbg9XXqApVALHCc+SEULttxMhqcSnRnICQBPJfyXRStHu8QB1ICZE2FGgb0a3E1f34iepREnoEmNc0fynz9ED2KVQN/HxKzuXa1n8cQipZQOwOm0cuVu4G1UMZuRy6C4rvVr18ZR9jhO5huKBL0="
    secret_access_key: &secret_access_key_production
      secure: "zr3MpjgkrcxubfeEaUToHZvUHwVg4dRf9d9echXQLZl/qVb3srmo07SFlEzpPCCofcvIW0A8B3d3+9zN3eRTiUZCfWyL9MNpwGvYhjb9TfuPJKfYhy/201yTlNJjxjrTZ7i1nL/k+aqpcRR5yUXoF8hA/KCx4anFklGuOn42oWoA0R5EBf4tDhV6/Hzz8UR155zAiUpt5CWYqEgYp3QoBHfmDTqyHm8QRaaMxkR66OXoa5e3wuPhGZE78/X7SlHM8mwVKNejNrwoF2Szw0Viv2mRb+bj0UyYmA88efQoo5A6GQt7io0U+oeHFShKEUJVWyBvg72S6jXklAH/nGPdFC1CLEP9Hb9S4oxY70r2DwS8sHlccioycVTear1YQ7iuAiU52yorin3XiJv/tI041ZR0/ZEH7Q5FBbkph9EeXJs5FdCL++bj9a5Pf19qltWoKvEBG7Gg8pRIuby+U7Rt4hHy767wDBMKA0eALqogNcFluRlr/E1rPegdPmvL5FsvWPwm9HYVMi8PM79CTKnpYkZBAYoI+lRTTL4u1QonoVSu8dQvU1X1TYmRAak5GyIAIzllW9l3H++zOY0piNBilqOUNfX2AnCHbHR9yNMvkiGxMwQUeZ9F+s6K031gx1GBT486gnZ0Jltzdrl/qXk5R4s1RMGX+HaFTSeyeySkUcg="
    local_dir: deploy_code_upload
    skip_cleanup: true
    on: &deploy_on_production
      branch: master
    bucket: &s3_bucket_production
      secure:  "Rpue8M7F8mHruJQhlBpAL9DMOQqd/O71XUXTVp5jGBvvv+pfM0to4eI6XpGNekRiSid2tiOY8+dG1OPAe4GFjQ/8B+wGnnIq37KzyQZUP4fGkfixaLmv6Fs5JS97Fs19DgWSt3P3Ov+k379Htd8+b1HkaDfOTBm9DMWbwbTfnrftS0q64kxP5pN/Xin+7x055zwa/YOrI182Ts70X2YQ56NMLFjAaXpvIln2VFYBOuEsXBVmwG1N+n2eZrvBCNfk5D8jgoffcHGVXhY1TvR9EnCzaPs9uZ+5YrI/H1NIjXXZ67Jn99dLY1XE+I0JsE2PjnbcLvhwPhD67RLu8orXir1cLeY2LZSW37j3tfjkoaS1dnvNVFVOL+l31teigbe8ZgxqNBQxyiQY/7Zr3Uu+0OtgIUQYv1PprJIcNfFFgukp6J5LgGrWbHH4AHyCQh13veWT4t3gRMWXWxFiPxmnR+1WkiosYEckAyN6wxOTHrMiFIFhfdFOBkhtQys/sTylUU1iCjMt0E5MKO3XVOEkfe5QG0UiZJYT7tbH1xByPlSWgFQ45dig+d+lBavH6HnhbwqrDltW/zSpYT+t1a+cG1caCXRk/4Po46HIXMkuPjxcFjujTSWKpUbcgzZcdtZ2SyCAYe7MNlgBNvkIjDFaZrURY28IGffG28XgA1p5MhE="
    region: us-west-2
  - provider: codedeploy
    access_key_id: *access_key_id_production
    secret_access_key: *secret_access_key_production
    bucket: *s3_bucket_production
    region: us-west-2
    key: "$TRAVIS_COMMIT.zip"
    bundle_type: zip
    application: &application_production
      secure: "YXWlfHjYqq/TJenXSCs0p5CHjqwRQN9okmbalGGylyuApwWHAGtCRQzt5mEPrZCAyM5iq0HabQT7hD+gxsSDzJuvxlumJGRLEtG2IYi+IwUgwdsXm4LsMco5JXC79DA++nKnac6QWbpbpuBbKJDnlCUJ4nE2ZLHTfM+gY3xzwdfbZpVDcXmtg1HE0NrqjRmGluV17iWSsq1swaPpzITE5xEa7qYgbX5Od0rvJT2V+CSyM68VQGNdVqB+nfh+ZalbLDLCzPXEF9OzZxMsxo4+zi31prtIRoS2mFdMTIlmy9fBm8QG2nSOGGHQKOMVSKYKfP4Je33aSGW5ltERNKsd9ibVBdZY1ovHY/rx8w4t+po83W4gkMC7OTFKZ0boK/ZHKoW0Km9fOK+p7PMCAoMqioAROzhLm18HOHrSDRgt2PDQICf2QapZoLjPbABzomAoR7MU+7rlwfkn6Htz8JVe5VE9l+MXfChN/5NyCvgmyu0u76uSBGguNKlmjEWI/TXTwLcY/iT7Mb1hIdFzLrbLfG2CmNFbrP4GEraws+hazotdFJ1y4Rx0h3U1g2DOc/NRq/EuXNdxXR8UPY7xNJ+LupB64uqdG3J4tb7rXbt/pPxi7vJ9zBLt6p0z0Xn+VQ1+7D0BPdMrFMwU5u8KuZE9bOwXezGVM2P/c04vNayAOS0="
    deployment_group: *application_production
    on: *deploy_on_production
